name: ETF Analysis & Dashboard

on:
  schedule:
    - cron: '0 10 * * 1-5'  # UTC 10:00 = 台北時間 18:00 (工作日)
  workflow_dispatch:  # 允許手動執行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  analyze-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests pandas numpy
        
    - name: Create directories
      run: |
        mkdir -p docs
        mkdir -p temp_data
        
    - name: Run ETF Firebase Analysis
      env:
        FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      run: |
        echo "🚀 開始執行ETF Firebase分析..."
        python scripts/etf_analyzer.py
        
    - name: Generate Dashboard
      env:
        FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      run: |
        echo "🌐 生成儀表板網頁..."
        python scripts/generate_dashboard.py
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Analysis Summary
      run: |
        echo "✅ ETF分析完成"
        echo "📊 資料已儲存至Firebase"
        echo "🌐 儀表板已部署至GitHub Pages"
        echo "🔗 網址: ${{ steps.deployment.outputs.page_url }}"
        echo "⏰ 執行時間: $(date)"
